cdxa-imprint: Add missing fpos conversion for MSVC
This is intended to fix the following MSVC error:

  cmd_cdxa_imprint.cc(51): error C2666: 'std::fpos<_Mbstatet>::operator !=': 2 overloads have similar conversions