Fix MSVC compile error in edit_asset_propctl.cc
This fixes the following error, presumably caused by a bug in the MSVC
compiler:

    error C3646: 'h_change': unknown override specifier